-- MedControl — Script de criação do banco no Supabase
-- Execute no SQL Editor do seu projeto Supabase

create table if not exists medicamentos (
  id bigint generated by default as identity primary key,
  nome text not null,
  dose text not null,
  horarios text[] not null,
  created_at timestamptz default now()
);

-- Habilita Row Level Security (boa prática)
alter table medicamentos enable row level security;

-- Política: permite leitura e escrita sem autenticação (anon key)
-- Em produção real, recomenda-se restringir por usuário autenticado
create policy "acesso_publico" on medicamentos
  for all using (true) with check (true);